# Generated by Django 5.2 on 2025-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del departamento (ej: Recursos Humanos)', max_length=50, unique=True, verbose_name='Nombre del Departamento')),
                ('sigla', models.CharField(help_text='Sigla identificatoria (ej: RRHH)', max_length=10, unique=True, verbose_name='Sigla')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=60, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el departamento está operativo', verbose_name='¿Está activo?')),
                ('piso', models.PositiveSmallIntegerField(blank=True, help_text='Número de piso donde se ubica', null=True, verbose_name='Piso')),
                ('oficina', models.CharField(blank=True, help_text='Número/identificador de oficina', max_length=10, verbose_name='Oficina')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos de la empresa',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='departament_nombre_10b1e3_idx'), models.Index(fields=['sigla'], name='departament_sigla_160a47_idx'), models.Index(fields=['activo'], name='departament_activo_b4483a_idx')],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'sigla'), name='unique_nombre_sigla')],
            },
        ),
    ]
